sportsbooks: ["draftkings", "fanduel", "betmgm"]
region: us
min_edge: 0.3
max_tickets: 8
parlay_sizes: [2,3]
beam_width: 50
team_exposure_cap: 0.35
bankroll: 1000
kelly_fraction: 0.5
candidate_pool_size: 50
ttl_seconds: 300
rho: 0.02
