sportsbooks: ["draftkings", "fanduel", "betmgm"]
region: us
min_edge: 0.0
max_tickets: 8
parlay_sizes: [3,4,5,6,7,8,9,10]
beam_width: 50
team_exposure_cap: 0.35
bankroll: 1000
kelly_fraction: 0.5
candidate_pool_size: 50
ttl_seconds: 300
rho: 0.0
